version: "3.9"

services:
  pdf_parser:
    build: .
    container_name: pdf_parser
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    networks:
      - laravel-production

networks:
  laravel-production:
    driver: bridge
