version: "3.8"

services:
  pdf_parser:
    build: .
    container_name: pdf_parser
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    networks:
      - AssetAccounting_laravel-production

networks:
  AssetAccounting_laravel-production:
    external: true
